title: Guillermo
description: Personal site for Guillermo Cabrera built with SASS / COMPASS / SUSY

url: http://www.guicaro.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about.html
# - title: Projects
#   url: /projects.html
 - title: Resume
   url: /resume.html
 - title: Contact 
   url: /contact.html

social:
   github: guicaro
   twitter: guicaro
   email: guicabrera@gmail.com

google_analytics: "UA-71275496-1"
