title: Guillermo
description: Personal site for Guillermo Cabrera

url: http://www.guicaro.com
baseurl: ""
permalink: blog/:title/

markdown: kramdown
highlighter: rouge

compress_html:
  clippings: all
  comments: [""]
  endings: [html, head, body, li, dt, dd, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]
  profile: false
  blanklines: false
  ignore:
    envs: []

navigation:
 - title: Home
   url: /
 - title: Blog
   url: /blog/
 - title: Projects
   url: /projects
 - title: About
   url: /about
 - title: Resume
   url: /resume
 - title: Contact 
   url: /contact

social:
   twitter: guicaro
   email: guicabrera@utexas.edu

google_analytics: "UA-71275496-1"
