title: Guillermo
description: Personal site for Guillermo Cabrera built with SASS / COMPASS / SUSY

url: http://www.guicaro.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index
 - title: About
   url: /about
 - title: Projects
   url: /projects
 - title: Resume
   url: /resume
 - title: Contact 
   url: /contact

social:
   github: guicaro
   twitter: guicaro
   email: guicabrera@utexas.edu

google_analytics: "UA-71275496-1"
